engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
        mass_threshold: 40
  fixme:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- server/test/