language: node_js
node_js:
    - "9"
install:
    - npm install
branches:
  only:
    - develop
    - api-test
    - staging
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - createdb travis_ci_test -U postgres
  - sequelize db:migrate
script: npm test
after_success:
  - npm run coveralls
after_script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=1LqYqgo8Da9hnzuSe1AV8P0SkIuilXTSu
email: false