language: node_js
node_js:
    - "6.11.0"
install:
    - npm install
branches:
  only:
    - develop
    - api-test
    - frontend_app
script: npm test
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - createuser dinobi -s -U postgres
  - createdb testdb --username=dinobi
  - NODE_ENV=test sequelize db:migrate:undo:all
  - NODE_ENV=test sequelize db:migrate
after_success:
  - npm run coveralls
after_script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=1LqYqgo8Da9hnzuSe1AV8P0SkIuilXTSu
email: false