language: node_js
node_js:
    - "6.11.0"
install:
    - npm install
branches:
  only:
    - develop
    - api-test
    - frontend_app
script: npm test
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sequelize db:migrate
after_success:
  - npm run coveralls
after_script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
notifications:
email: false