language: node_js
node_js:
    - "6.11.0"
install:
    - npm install
branches:
  only:
    - master
    - Test_cases
script: npm test
services:
  - postgresql
env:
  - NODE_ENV=production
before_script:
  - npm install -g sequelize-cli
  - export DATABASE_URL=postgres://auxtpnwe:KYs5AX1FatIBRvm8NDV8MlLqhgurJ8Or@echo.db.elephantsql.com:5432/auxtpnwe
  - sequelize db:migrate
after_script:
 - nyc npm test && nyc report --reporter=text-lcov | coveralls
after_success:
- npm run coveralls
after_script:
 - nyc npm test && nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=1LqYqgo8Da9hnzuSe1AV8P0SkIuilXTSu
email: false