language: node_js
node_js:
    - "6.11.0"
install:
    - npm install
branches:
  only:
    - master
    - Test_cases
    - Optimize_frontend
script: npm test
services:
  - postgresql
env:
  - NODE_ENV=production
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sequelize db:migrate
after_success:
  - npm run coveralls
after_script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=1LqYqgo8Da9hnzuSe1AV8P0SkIuilXTSu
email: false